### ISSUE TITLE
Program Issues

### ISSUE THREAD

**Issue by SuzanaKamis** [Danclarke98/PlantMonitoring#1]
Hi there, im trying out your program and running some issues.

C:\Users\Serenity\Downloads\PlantMonitoring-master\Django Web App>python manage.py testserver
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\commands\testserver.py", line 34, in handle
    db_name = connection.creation.create_test_db(verbosity=verbosity, autoclobber=not interactive, serialize=False)
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py", line 204, in __getitem__
    self.ensure_defaults(alias)
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py", line 172, in ensure_defaults
    conn = self.databases[alias]
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\conf\__init__.py", line 76, in __getattr__
    self._setup(name)
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\conf\__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\Serenity\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\conf\__init__.py", line 161, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by ctorD** [comment]
Hey there, this project is not being maintained at the moment but I'll try help you out. 

In _**Django Web App/untitled2/settings.py**_  there is multiple config options. 

You will find that SECRET_KEY is set to an environment variable. This environment variable probably does not exist on your machine. 

I would recommend generating a new Django Secret Key and setting it equal to that.

Like so: `SECRET_KEY = 'NEW_GENERATED_KEY'`

Django secret generator: https://miniwebtool.com/django-secret-key-generator/
